
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\nQ\x07<\xe2\x11H\xed8\x16\x06\x931\xb0\xd4P'
    
_lr_action_items = {'DASH':([1,6,],[4,8,]),'NAME':([0,2,8,9,],[1,1,9,1,]),'NUMBER':([4,],[6,]),'LBRACKET':([0,2,9,],[2,2,2,]),'RBRACKET':([5,7,9,10,],[7,-1,-3,-2,]),'$end':([3,7,9,10,],[0,-1,-3,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,9,],[3,5,10,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> LBRACKET expression RBRACKET','expression',3,'p_expression_bar','parser.py',7),
  ('expression -> NAME DASH NUMBER DASH NAME expression','expression',6,'p_expression_notes','parser.py',11),
  ('expression -> NAME DASH NUMBER DASH NAME','expression',5,'p_expression_note','parser.py',16),
]
