
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'j\xf9~;\x0e|\xd5Mj\x01skyU|\xcd'
    
_lr_action_items = {'DASH':([7,8,16,],[12,13,-9,]),'LPARAN':([19,],[21,]),'RPARAN':([22,],[23,]),'NUMBER':([4,12,13,14,21,],[9,16,18,19,22,]),'LBRACKET':([0,5,11,19,23,],[3,3,3,-4,-3,]),'LETTER':([0,3,17,18,],[4,7,7,-10,]),'RBRACKET':([6,17,18,20,],[11,-8,-10,-7,]),'POST':([9,],[14,]),'$end':([1,2,10,11,15,],[-2,0,-1,-6,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'bars':([0,5,11,],[1,10,15,]),'compostion':([0,],[2,]),'notes':([3,17,],[6,20,]),'pitch':([3,17,],[8,8,]),'duration':([13,],[17,]),'prelude':([0,],[5,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> compostion","S'",1,None,None,None),
  ('compostion -> prelude bars','compostion',2,'p_compostion','parser.py',11),
  ('compostion -> bars','compostion',1,'p_compostion','parser.py',12),
  ('prelude -> LETTER NUMBER POST NUMBER LPARAN NUMBER RPARAN','prelude',7,'p_prelude','parser.py',22),
  ('prelude -> LETTER NUMBER POST NUMBER','prelude',4,'p_prelude','parser.py',23),
  ('bars -> LBRACKET notes RBRACKET bars','bars',4,'p_bars_notes','parser.py',34),
  ('bars -> LBRACKET notes RBRACKET','bars',3,'p_bars_notes','parser.py',35),
  ('notes -> pitch DASH duration notes','notes',4,'p_notes_pitch_duration','parser.py',47),
  ('notes -> pitch DASH duration','notes',3,'p_notes_pitch_duration','parser.py',48),
  ('pitch -> LETTER DASH NUMBER','pitch',3,'p_pitch_terminals','parser.py',56),
  ('duration -> NUMBER','duration',1,'p_duration_terminals','parser.py',60),
]
